#!/home/ider/.local/share/virtualenvs/api-pdf2htmlex-wxY90yvb/bin/python

import requests
import sys
import json
import zipfile
import tempfile

api_urls = ['http://localhost:5000/pdf2htmlEX','http://192.168.1.220:5000/pdf2htmlEX']

def remote_convert(src, argv):

    for url in api_urls:
        try:
            files = {'file': open(src, 'rb')}
            data= {'command':json.dumps(' '.join(argv))}
            req = requests.post(url, files=files, data=data)
        except requests.exceptions.ConnectionError:
            continue
        if req.status_code == 200:
            break
    else:
        raise Exception('remote api is not available! %s'%req.text)
    fp = tempfile.TemporaryFile()
    fp.write(req.content)
    fp.seek(0)
    return fp


file_desc = sys.argv[-1]
argv = sys.argv
if '--dest-dir' in argv:
    idx = argv.index('--dest-dir')
    dst = argv[idx+1] if not argv[idx+1].startswith('-') else None
    del(argv[idx])
    del(argv[idx])
else:
    dst = './'
src = argv[-1] if not argv[-1].startswith('-') else None
assert(src)

del(argv[0])
del(argv[-1])

fp = remote_convert(src, argv)

with zipfile.ZipFile(fp, 'r') as myzip:
    myzip.extractall(dst)

# print(sys.argv)
